<regex> ::= <term>* ("|" <regex>)?
<term> ::= <atom> ("*" | "+" | "?")?
<atom> ::= <literal> | "(" <regex> ")" | "[" <class> "]" | "." | "^" | "$"
<literal> ::= "\\" <escaped> | ? ' ' to '~' except <metachar> ?
<escaped> ::= "a" | "b" | "f" | "n" | "r" | "t" | "v" | "x" <hexbyte> | <metachar>
<hexbyte> ::= (? '0' to '9' or 'a' to 'f' or 'A' to 'F' ?){2}
<metachar> ::= "\\" | "." | "^" | "$" | "*" | "+" | "?" | "[" | "]" | "(" | ")" | "|"
<class> ::= "^"? (<literal> ("-" <literal>)?)*
